name: Catify
description: A funny app about cats!
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+1
  cached_network_image: 0.7.0
  charts_flutter: 0.6.0
  carousel_slider: 1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - asset/default-placeholder.png
  fonts:
    - family: ProximaNovaSoft
      fonts:
        - asset: fonts/ProximaNovaSoft-Regular.ttf
        - asset: fonts/ProximaNovaSoft-Bold.ttf
          weight: 700